strength_log/maxes/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, DecimalField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired
from datetime import datetime


class MaxesForm(FlaskForm):
    squat = DecimalField("Squat Max", validators=[DataRequired()], default=315.0)
    bench = DecimalField("Bench Max", validators=[DataRequired()], default=225.0)
    deadlift = DecimalField("Deadlift Max", validators=[DataRequired()], default=405.0)
    press = DecimalField("Press Max", validators=[DataRequired()], default=135.0)
    submit = SubmitField("Submit")


class DateForm(FlaskForm):
    start_date = DateField("Start Date", format="%Y-%m-%d", default=datetime.today)
    end_date = DateField("End Date", format="%Y-%m-%d", default=datetime.today)
    date_submit = SubmitField("Filter Charts")

    def validate_on_submit(self):
        result = super(DateForm, self).validate()
        if self.start_date.data > self.end_date.data:
            return False
        else:
            return result

strength_log/personal_records/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, DecimalField, FieldList, FormField


class RepForm(FlaskForm):
    one_rep = DecimalField("One Rep", default=0)
    two_reps = DecimalField("Two Reps", default=0)
    three_reps = DecimalField("Three Reps", default=0)
    four_reps = DecimalField("Four Reps", default=0)
    five_reps = DecimalField("Five Reps", default=0)


class PersonalRecordForm(FlaskForm):
    squat = FormField(RepForm)
    bench = FormField(RepForm)
    deadlift = FormField(RepForm)
    press = FormField(RepForm)

    submit = SubmitField("Submit")

strength_log/main/routes.py
from strength_log.models import Post, GeneralSetting
from strength_log.main.forms import FilterForm

from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import current_user
from loguru import logger

main = Blueprint("main", __name__)


@main.route("/")
def index():
    """Landing page."""
    posts_count = Post.query.count()
    posts = Post.query.all()
    total_reps = 0
    for post in posts:
        for single_set in post.sets:
            total_reps += single_set["reps"]

    return render_template("index.html", posts_count=posts_count, total_reps=total_reps)


@main.route("/home", methods=["GET", "POST"])
def home():
    """
    Homepage where the user will be able to view their logs.
    User can filter which logs they see based on main lift.
    """
    page = request.args.get("page", 1, type=int)
    posts = (
        Post.query.filter_by(author=current_user)
        .order_by(Post.timestamp.desc())
        .paginate(page=page, per_page=5)
    )
    settings = GeneralSetting.query.filter_by(user=current_user).first()
    if not settings:
        unit = "lbs"
    else:
        unit = settings.unit

    form = FilterForm()

    if request.method == "POST":
        """User request to filter logs by main lifts."""
        if form.validate_on_submit():
            return redirect(url_for("main.main_lift", lift=form.main_lift.data))

    if not posts.items:
        """If no items are in the users posts, redirect to log their first workout."""
        flash("To view workouts on your home page, log your first workout!", "info")
        return redirect(url_for("posts.new_post"))

    return render_template(
        "home.html", posts=posts, title="Home", form=form, filter_type="All", unit=unit,
    )


@main.route("/main_lift/<lift>", methods=["GET", "POST"])
def main_lift(lift):
    """
    Homepage with the logs filtered by main lift.
    User can filter which logs they see based on main lift.
    """
    page = request.args.get("page", 1, type=int)
    posts = (
        Post.query.filter_by(author=current_user, main_lift=lift)
        .order_by(Post.timestamp.desc())
        .paginate(page=page, per_page=5)
    )
    form = FilterForm()
    settings = GeneralSetting.query.filter_by(user=current_user).first()
    if not settings:
        unit = "lbs"
    else:
        unit = settings.unit

    capital_lift = lift.capitalize()

    if request.method == "POST":
        """User request to filter logs by main lifts."""
        if form.validate_on_submit():
            return redirect(url_for("main.main_lift", lift=form.main_lift.data))

    if not posts.items:
        """User has not logged a post with the main lift selected>"""
        flash(
            f"To view your {capital_lift} workouts, log your first {capital_lift} workout!",
            "info",
        )
        return redirect(url_for("posts.new_post"))

    return render_template(
        "home.html",
        posts=posts,
        title=capital_lift,
        form=form,
        filter_type=capital_lift,
        unit=unit,
    )


@main.route("/about")
def about():
    """General about page for Strength Log"""
    return render_template("about.html", title="About")


@main.route("/max_calculator")
def max_calculator():
    """Page where users can calculate their max lift."""
    if current_user.is_anonymous:
        unit = "lbs"
    else:
        settings = GeneralSetting.query.filter_by(user=current_user).first()
        if not settings:
            unit = "lbs"
        else:
            unit = settings.unit

    return render_template(
        "max_calculator.html", title="One-Rep Max Calculator", unit=unit
    )

strength_log/personal_records/routes.py
from strength_log import db
from strength_log.personal_records.forms import PersonalRecordForm
from strength_log.models import (
    SquatPersonalRecord,
    BenchPersonalRecord,
    DeadliftPersonalRecord,
    PressPersonalRecord,
    User,
    GeneralSetting,
)

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from loguru import logger


personal_records = Blueprint("user_personal_records", __name__)


@personal_records.route("/personal_records", methods=["GET", "POST"])
@login_required
def new_personal_records():
    user = User.query.get(current_user.id)

    if not user.authenticated:
        flash("Account must be authenticated to access Personal Records.", "danger")
        return redirect(url_for("main.index"))

    if request.method == "POST":
        form = PersonalRecordForm()
        if form.validate_on_submit():
            squat_record = SquatPersonalRecord(
                one_rep=form.squat.data["one_rep"],
                two_reps=form.squat.data["two_reps"],
                three_reps=form.squat.data["three_reps"],
                four_reps=form.squat.data["four_reps"],
                five_reps=form.squat.data["five_reps"],
                lifter=current_user,
            )
            bench_record = BenchPersonalRecord(
                one_rep=form.bench.data["one_rep"],
                two_reps=form.bench.data["two_reps"],
                three_reps=form.bench.data["three_reps"],
                four_reps=form.bench.data["four_reps"],
                five_reps=form.bench.data["five_reps"],
                lifter=current_user,
            )
            deadlift_record = DeadliftPersonalRecord(
                one_rep=form.deadlift.data["one_rep"],
                two_reps=form.deadlift.data["two_reps"],
                three_reps=form.deadlift.data["three_reps"],
                four_reps=form.deadlift.data["four_reps"],
                five_reps=form.deadlift.data["five_reps"],
                lifter=current_user,
            )
            press_record = PressPersonalRecord(
                one_rep=form.press.data["one_rep"],
                two_reps=form.press.data["two_reps"],
                three_reps=form.press.data["three_reps"],
                four_reps=form.press.data["four_reps"],
                five_reps=form.press.data["five_reps"],
                lifter=current_user,
            )

            db.session.add(squat_record)
            db.session.add(bench_record)
            db.session.add(deadlift_record)
            db.session.add(press_record)

            db.session.commit()

            flash("Your PR was successfully logged.", "success")

            return redirect(url_for("main.home"))

    user_squat_records = SquatPersonalRecord.query.filter_by(
        user_id=current_user.id
    ).first()

    user_bench_records = BenchPersonalRecord.query.filter_by(
        user_id=current_user.id
    ).first()

    user_deadlift_records = DeadliftPersonalRecord.query.filter_by(
        user_id=current_user.id
    ).first()

    user_press_records = PressPersonalRecord.query.filter_by(
        user_id=current_user.id
    ).first()

    form = PersonalRecordForm(
        squat=user_squat_records,
        bench=user_bench_records,
        deadlift=user_deadlift_records,
        press=user_press_records,
    )
    settings = GeneralSetting.query.filter_by(user=current_user).first()
    if not settings:
        unit = "lbs"
    else:
        unit = settings.unit

    if not user_press_records:
        """If the user has not submitted PR's, share a tip with a info message."""
        flash(
            "Tip: Use Personal Records to track your all-time best lifts on reps 1-5. This is usually not the values you base your programming on, track that in the training max tab.",
            "info",
        )

    return render_template(
        "personal_records.html", form=form, title="Personal Records", unit=unit
    )

strength_log/posts/routes.py
from datetime import datetime, time
from strength_log import db
from strength_log.posts.forms import PostForm, DeleteForm, UpdateForm
from strength_log.models import Post, AccessoryLift, GeneralSetting

from flask import render_template, redirect, url_for, Blueprint, flash, request, abort
from flask_login import current_user, login_required

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    accessory_lifts = [
        a.lift
        for a in AccessoryLift.query.filter(
            (AccessoryLift.user_id == None) | (AccessoryLift.user_id == current_user.id)
        ).order_by(AccessoryLift.lift)
    ]
    if request.method == "POST":
        if form.validate():
            post = Post(
                title=form.title.data,
                warm_up=form.warm_up.data,
                main_lift=form.main_lift.data,
                sets=form.sets.data,
                accessories=form.accessories.data,
                conditioning=form.conditioning.data,
                author=current_user,
            )
            db.session.add(post)
            db.session.commit()

            flash(f"Your {form.main_lift.data} workout has been logged!", "success")
            return redirect(url_for("main.home"))
        else:
            flash("Workout failed to submit, check fields for missing data.", "danger")

    return render_template(
        "create_post.html",
        form=form,
        title="New Post",
        accessory_lifts=accessory_lifts,
    )


@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    form = DeleteForm()

    post = Post.query.get_or_404(post_id)

    settings = GeneralSetting.query.filter_by(user=current_user).first()
    if not settings:
        unit = "lbs"
    else:
        unit = settings.unit

    return render_template("post.html", post=post, form=form, unit=unit)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id: int):
    post: Post = Post.query.get_or_404(post_id)

    accessory_lifts_options = [a.lift for a in AccessoryLift.query.all()]

    if post.author != current_user:
        abort(403)

    form = UpdateForm()

    if form.validate_on_submit():
        workout_date = form.date.data
        current_utc = post.timestamp
        current_utc_time_only = time(
            hour=current_utc.hour,
            minute=current_utc.minute,
            second=current_utc.second,
            microsecond=current_utc.microsecond,
            tzinfo=current_utc.tzinfo,
        )
        workout_datetime = datetime.combine(workout_date, current_utc_time_only)

        post.title = form.title.data
        post.warm_up = form.warm_up.data
        post.main_lift = form.main_lift.data
        post.sets = form.sets.data
        post.accessories = form.accessories.data
        post.conditioning = form.conditioning.data
        post.timestamp = workout_datetime

        db.session.commit()
        flash("Updated!", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.warm_up.data = post.warm_up
        form.main_lift.data = post.main_lift
        form.conditioning.data = post.conditioning

    return render_template(
        "update_post.html",
        main_sets=post.sets,
        form=form,
        title="Update Workout",
        legend="Update Workout",
        accessory_lifts_options=accessory_lifts_options,
        accessory_lifts=post.accessories,
        workout_date=post.timestamp.strftime("%Y-%m-%d"),
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))

strength_log/training_volume/routes.py
from collections import namedtuple
from datetime import date
from dateutil.relativedelta import relativedelta
from flask import redirect, url_for, flash, render_template
from flask.blueprints import Blueprint
from flask_login import current_user
from flask_login.utils import login_required
from loguru import logger
import pandas as pd

from strength_log.models import Post, User, GeneralSetting

training_volume = Blueprint("training_volume", __name__)

TrainingVolume = namedtuple("TrainingVolume", ["lift", "date", "volume"])


@training_volume.route("/training-volume")
@login_required
def view_training_volume():
    user = User.query.get(current_user.id)

    # Check if the user is not authenticated from email, do not give access
    if not user.authenticated:
        flash("Account must be authenticated to access Training Volume.", "danger")
        return redirect(url_for("main.index"))

    six_months_ago = date.today() - relativedelta(months=6)
    logger.debug(six_months_ago)

    posts = Post.query.filter(
        Post.author == current_user, Post.timestamp >= six_months_ago
    )

    squat_training_volumes = list()
    bench_training_volumes = list()
    deadlift_training_volumes = list()
    press_training_volumes = list()

    for post in posts:
        volume = 0
        main_lift = post.main_lift

        for single_set in post.sets:
            volume += single_set.get("reps") * single_set.get("weight")

        if main_lift == "squat":
            squat_training_volumes.append(
                TrainingVolume(main_lift, post.timestamp, volume)
            )
        elif main_lift == "bench":
            bench_training_volumes.append(
                TrainingVolume(main_lift, post.timestamp, volume)
            )
        elif main_lift == "press":
            press_training_volumes.append(
                TrainingVolume(main_lift, post.timestamp, volume)
            )
        else:
            deadlift_training_volumes.append(
                TrainingVolume(main_lift, post.timestamp, volume)
            )

    label_string_format = "%m-%d-%y"
    if len(squat_training_volumes) > 0:
        squat_df = pd.DataFrame.from_records(
            squat_training_volumes, columns=TrainingVolume._fields
        )
        squat_df = squat_df.resample("W", on="date").sum().reset_index()
        squat_training_volumes = [
            TrainingVolume("squat", row.date.strftime(label_string_format), row.volume)
            for _, row in squat_df.iterrows()
        ]

    if len(bench_training_volumes) > 0:
        bench_df = pd.DataFrame.from_records(
            bench_training_volumes, columns=TrainingVolume._fields
        )
        bench_df = bench_df.resample("W", on="date").sum().reset_index()
        bench_training_volumes = [
            TrainingVolume("bench", row.date.strftime(label_string_format), row.volume)
            for _, row in bench_df.iterrows()
        ]

    if len(press_training_volumes) > 0:
        press_df = pd.DataFrame.from_records(
            press_training_volumes, columns=TrainingVolume._fields
        )
        press_df = press_df.resample("W", on="date").sum().reset_index()
        press_training_volumes = [
            TrainingVolume("press", row.date.strftime(label_string_format), row.volume)
            for _, row in press_df.iterrows()
        ]

    if len(deadlift_training_volumes) > 0:
        deadlift_df = pd.DataFrame.from_records(
            deadlift_training_volumes, columns=TrainingVolume._fields
        )
        deadlift_df = deadlift_df.resample("W", on="date").sum().reset_index()
        deadlift_training_volumes = [
            TrainingVolume(
                "deadlift", row.date.strftime(label_string_format), row.volume
            )
            for _, row in deadlift_df.iterrows()
        ]

    settings = GeneralSetting.query.filter_by(user_id=user.id).first()
    if not settings:
        unit = "lbs"
    else:
        unit = settings.unit

    return render_template(
        "training-volume.html",
        title="Weekly Training Volume",
        squat_volume=squat_training_volumes,
        bench_volume=bench_training_volumes,
        deadlift_volume=deadlift_training_volumes,
        press_volume=press_training_volumes,
        unit=unit,
    )

strength_log/templates/about.html
{% extends "base.html" %}
{% block app_content %}
    <div>
        <h1 class="text-center">About Strength Log</h1>
    </div>
    <br>
    <div class="mx-5">
        <h3>Strength log was created to make logging your strength workouts simple and fast. 
            Many workout logging applications are too general for strength athletes. Too many choices or settings keeps the
            focus off what is important. <b>Training!</b>
        </h3>
    </div>
    <br><br>
    <div class="mx-5">
        <h3>Strength Log is ideal for athletes who train in similar ways to popular programs such as 5/3/1, The Texas Method, GZCL, etc.. 
            Strength Log assumes you include a warm up, a main strength lift, accessory/assistance lifts and conditioning each and every day.</h3>
    </div>
    <br><br>
    <div class="mx-5">
        <h3>Have questions about Strength Log? Want to share your ideas on improving Strength Log? Contact
            <a href="mailto:contact.strength.log@gmail.com">Strength Log</a>. Strength Log wants to hear from you!
        </h3>
    </div>
{% endblock %}

strength_log/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block head %}
{{super()}}
<link rel="shortcut icon" href="{{ url_for('static', filename='assets/favicon.ico') }}">
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}">
{% endblock %}

{% block title %}
  {% if title %}{{ title }} - Strength Log{% else %}Welcome to Strength Log{% endif %}
{% endblock %}

{% block navbar %}
  <nav class="navbar navbar-default navbar-custom">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">
          <img src="{{ url_for('static', filename='assets/logo.png') }}" width="30" height="30" alt="logo" class="d-inline-block align-top">
        </a>
        <a href="{{ url_for('main.index') }}" class="navbar-brand">Strength Log</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-custom">
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('main.home') }}">Home</a></li>
          <li><a href="{{ url_for('posts.new_post') }}">Log Workout</a></li>
          <li><a href="{{ url_for('user_personal_records.new_personal_records') }}">PR's</a></li>
          <li><a href="{{ url_for('maxes.new_max') }}">Training Max</a></li>
          <li><a href="{{ url_for('training_volume.view_training_volume') }}">Training Volume</a></li>
          {% endif %}
          <li><a href="{{ url_for('main.max_calculator') }}">One-Rep Max Calculator</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_anonymous %}
          <li><a href="{{ url_for('users.login') }}">Login</a></li>
          <li><a href="{{ url_for('users.register') }}">Register</a></li>
          {% else %}
          <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
          <li><a href="{{ url_for('users.settings') }}">Settings</a></li>
          {% endif %}
          <li><a href="{{ url_for('main.about') }}">About</a></li>

      </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block content %}
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
              {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container-fluid">
      <div class="panel panel-default">
        <div class="panel-body">
          {% block app_content %}{% endblock %}
        </div>
      </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

strength_log/templates/confirm_email.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Resend Confirmation Email</h1>
    <div class="row">
        <div class="col-md-4">
            <form class="form" method="POST" action="{{url_for('users.resend_confirm_email')}}">
                {{ form.hidden_tag() }}
                {{ wtf.form_errors(form, hiddens="only") }}
                {{ wtf.form_field(form.email)}}
                {{ wtf.form_field(form.submit)}}
            </form>
        </div>
    </div>
{% endblock %}

strength_log/templates/create_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
{% endblock %}


{% block app_content %}
{% if legend %}
    <h1>{{ legend }}</h1>
{% else %}
    <h1>Log Workout</h1>
{% endif %}

<form class="form" method="POST" action="">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    {% if form.title.errors %}
    {{ wtf.form_field(form.title) }}
    <div class="invalid-feedback">
        {% for error in form.title.errors %}
        <span>{{ error }}</span>
        {% endfor %}
    </div>
    {% else %}
    {{ wtf.form_field(form.title) }}
    {% endif %}

    {{ wtf.form_field(form.warm_up) }}
    <!-- Main Lift Subform -->
    <div class="panel panel-default">
        <div class="panel-body">
            {{ wtf.form_field(form.main_lift) }}
            <div>
                <button type="button" class="btn btn-primary" value="Add" onclick="add();">Add Set</button>
                <button type="button" class="btn btn-secondary" value="Remove" onclick="remove();">Remove Set</button>
            </div>
            <br>
            <div id="main-subform-container" class="form-inline">
                {% for subform in form.sets %}
                <div id="set-{{ loop.index0 }}-form" class="subform" data-index="{{ loop.index0 }}">
                    <label id="sets-0-label" class="control-label lift-label">Set: {{loop.index}}</label>
                    {{ subform.reps(class="form-control", type="number", placeholder="Reps") }}
                    {{ subform.weight(class="form-control", type="number", placeholder="Weight") }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div id="set-_-form" class="hidden" data-index="_">
        <label id="sets-_-label" class="lift-label"></label>
        <input class="form-control" id="sets-_-reps" name="sets-_-reps" type="number" placeholder="Reps">
        <input class="form-control" id="sets-_-weight" name="sets-_-weight" type="number" placeholder="Weight">
    </div>
    <br>
    <!-- Accessories Subform -->
    <div class="panel panel-default">
        <div class="panel-body">
            <label class="control-label">Accessories</label>
            <div>
                <button type="button" class="btn btn-primary" value="Add" onclick="add_accessory({{ accessory_lifts|safe }});">
                    Add Accessory
                </button>
                <button type="button" class="btn btn-secondary" value="Remove" onclick="remove_accessory();">
                    Remove Accessory
                </button>
                <br>
                <small>
                    Don't see an accessory you performed? <a href="{{ url_for('users.settings') }}">Add it here!</a>
                </small>
            </div>
            <br>
            <div id="accessories-subform-container" class="form-inline"></div>
        </div>
    </div>
    <div id="accessories-_-form" class="hidden" data-index="_">
        <select class="form-control" id="accessories-_-lift" name="accessories-_-lift" ></select>
        <input class="form-control" id="accessories-_-sets" name="accessories-_-sets" type="number" placeholder="Sets">
        <input class="form-control" id="accessories-_-reps" name="accessories-_-reps" type="number" placeholder="Reps">
        <input class="form-control" id="accessories-_-weight" name="accessories-_-weight" type="number" placeholder="Weight">
        <br>
    </div>
    <br>
    {{ wtf.form_field(form.conditioning) }}
    {{ wtf.form_field(form.submit) }}
</form>
{% endblock %}

{% block scripts %}
<script src="{{url_for('static', filename='js/posts.js')}}"></script>
{{super()}}
{% endblock %}

strength_log/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Login</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <br>
    <a href="{{ url_for('users.reset_password_request') }}"> Trouble Signing In?</a>
{% endblock %}

strength_log/templates/post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}">
{% endblock %}

{% block app_content %}
	{% if post.author == current_user %}
		<div>
			<a class="btn" id="update_post" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update Post</a>
		</div>
		<br>
		<div>
			<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
				{{ form.hidden_tag() }}
				<input class="btn btn-danger" type="submit" value="Delete Post">
			</form>
		</div>
		<br>
	{% endif %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<a class="card-link" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
				<h5 class="pull-right">{{ moment(post.timestamp).fromNow() }}</h5>
			</div>
			<div class="panel-body">
				<h3>Warm Up</h3>
				<h5>{{ post.warm_up }}</h5>
				<h3>Main Lift</h3>
				<h5>{{ post.main_lift.capitalize() }}</h5>
				<table class="table table-condensed table-striped">
					<thead>
						<tr>
							<th scope="col">Set</th>
							<th scope="col">Reps</th>
							<th scope="col">Weight ({{ unit }})</th>
						</tr>
					</thead>
				<tbody>
					{% for set in post.sets %}
					<tr>
						<td>{{ loop.index }}</td>
						<td>{{ set["reps"] }}</td>
						<td>{{ set["weight"] }}</td>
					</tr>
					{% endfor %}
				</tbody>
				</table>
				<h3>Accessory Lifts</h3>
				<table class="table table-condensed table-striped">
					<thead>
						<tr>
							<th scope="col">Lift</th>
							<th scope="col">Sets</th>
							<th scope="col">Reps</th>
							<th scope="col">Weight ({{ unit }})</th>
						</tr>
					</thead>
				<tbody>
					{% for lift in post.accessories %}
					<tr>
						<td>{{ lift["lift"] }}</td>
						<td>{{ lift["sets"] }}</td>
						<td>{{ lift["reps"] }}</td>
						<td>{{ lift["weight"] }}</td>
					</tr>
					{% endfor %}
				</tbody>
				</table>
				{% if post.conditioning %}
					<h3>Conditioning</h3>
					<h5>{{ post.conditioning }}</h5>
				{% endif %}
			</div>
		</div>
{% endblock %}

strength_log/templates/register.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Register</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

strength_log/templates/reset_password_request.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}